### ISSUE TITLE
IndexOutOfRangeException when empty string is passed to `RealtimeDatabase.WriteValue()`

### ISSUE THREAD

**Issue by SrejonKhan** [SrejonKhan/FirebaseRestClient#6]
The following exception is thrown when we pass a zero-length/empty string to the `RealtimeDatabase.WriteValue()` method. 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array. 
at FirebaseRestClient.RealtimeDatabase.GenerateBody (System.Object value) [0x000ce] in ...Runtime\\RealtimeDatabase\\RealtimeDatabase.cs:889  
at FirebaseRestClient.RealtimeDatabase.WriteValue (System.Object value) [0x00012] in ...Runtime\\RealtimeDatabase\\RealtimeDatabase.cs:105
```
_Stacktrace trimmed for better readability._

**Comment by SrejonKhan** [comment]
The length of an empty string is zero. In the following condition, in the case of an empty string, it throws `IndexOutOfRangeException`.
https://github.com/SrejonKhan/FirebaseRestClient/blob/b33e9b600320f9bec7604ce6ef1b3f6ac891254d/Runtime/RealtimeDatabase/RealtimeDatabase.cs#L889

It can be fixed by simply adding one more condition to check if our string is empty.

**Comment by SrejonKhan** [comment]
The length of an empty string is zero. In the following condition, in the case of an empty string, it throws `IndexOutOfRangeException`.
https://github.com/SrejonKhan/FirebaseRestClient/blob/b33e9b600320f9bec7604ce6ef1b3f6ac891254d/Runtime/RealtimeDatabase/RealtimeDatabase.cs#L889

It can be fixed by simply adding one more condition to check if our string is empty.

**Comment by sagefhopkins** [comment]
https://github.com/SrejonKhan/FirebaseRestClient/pull/7

**Comment by sagefhopkins** [comment]
https://github.com/SrejonKhan/FirebaseRestClient/pull/8
